# Numpy

En python, al ser todo objetos, tiene el gran inconveniente de que los datos pesan muchos. <br>
Para representar un número entero necesitamos muchos bytes dado que tenemos que almacenar el número en sí junto con los métodos de la clase entero. Y así con el resto de datos.

Numpy (Numerical Python), es un módulo optimizado de tal forma que podemos realizar operaciones matriciales con más rapidez.

El principal tipo de dato que ofrece Numpy es ndarray (array o lista n-dimensional). Esta tiene la característica principal de que solo puede contener datos de un mismo tipo, números, letras, etc...; Pero no mezclado.

## Definición de ndarray según ChatGTP.

Para más info ver documentación oficial: https://numpy.org/doc/stable/

El objeto ndarray de NumPy tiene varios elementos importantes que te permiten acceder y manipular los datos almacenados en arreglos multidimensionales. Aquí tienes una lista breve de algunos de los elementos más importantes del objeto ndarray:

1. `shape`: Es una propiedad que devuelve la forma (dimensiones) del arreglo NumPy. Es una tupla que indica el tamaño de cada dimensión. Por ejemplo, `array.shape` devuelve `(3, 4)` para un arreglo de 3 filas y 4 columnas.

2. `dtype`: Es una propiedad que especifica el tipo de datos de los elementos en el arreglo. Por ejemplo, `array.dtype` devuelve `int32` para un arreglo de enteros de 32 bits.

3. Indexación de elementos: Puedes acceder a elementos individuales del arreglo utilizando corchetes `[ ]` y proporcionando los índices correspondientes a cada dimensión. Por ejemplo, `array[2, 1]` accede al elemento en la tercera fila y segunda columna.

4. Segmentación de arreglos: Puedes acceder a subarreglos o segmentos del arreglo utilizando la notación de segmentación. Por ejemplo, `array[:, 1:3]` accede a todas las filas y a las columnas 2 y 3 del arreglo.

5. Operaciones matemáticas: Puedes realizar operaciones matemáticas y funciones en los arreglos NumPy, como suma, resta, multiplicación, entre otras. Estas operaciones se aplican de forma vectorizada, lo que significa que se aplican a todos los elementos del arreglo de manera eficiente.

6. Funciones de agregación: NumPy proporciona funciones de agregación que operan en arreglos, como `sum()`, `mean()`, `max()`, `min()`, entre otras. Estas funciones calculan agregados a lo largo de una dimensión o de todo el arreglo.

7. Broadcasting: NumPy permite el broadcasting, que es una regla de compatibilidad de forma que permite operar entre arreglos con formas diferentes pero compatibles. Esto facilita las operaciones entre arreglos de diferentes dimensiones sin la necesidad de copiar datos.

Estos son solo algunos elementos importantes del objeto ndarray en NumPy. La biblioteca ofrece muchas más funcionalidades y métodos para trabajar con arreglos multidimensionales de manera eficiente y conveniente.

## Creación básica de una ndarray

In [10]:
import numpy as np

# Crear un ndarray de una dimensión
arr1d = np.array([1, 2, 3, 4, 5])
print(arr1d.shape)

# Crear un ndarray de dos dimensiones
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d.shape)

# Crear un ndarray de ceros de tamaño 3x3
zeros = np.zeros((3, 3))
print(zeros.shape)

# Crear un ndarray de unos de tamaño 2x4
ones = np.ones((2, 4))
print(ones.shape)

(5,)
(3, 3)
(3, 3)
(2, 4)


## Operaciones matemáticas básicas

In [12]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Sumar 2 a cada elemento del ndarray
arr_sum = arr + 2
print(arr_sum)

# Elevar al cuadrado cada elemento del ndarray
arr_square = arr ** 2
print(arr_square)

# Calcular la media de los elementos del ndarray
arr_mean = np.mean(arr)
print(arr_mean)

[3 4 5 6 7]
[ 1  4  9 16 25]
3.0


## Acceso a elementos particulares

In [16]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5])

# Obtener el primer elemento del ndarray
first_element = arr[0]
print(first_element)

# Obtener los elementos del ndarray desde el índice 1 al 3 (excluyendo el 3)
subset = arr[1:3]
print(subset)

# Obtener los elementos mayores que 3
greater_than_3 = arr[arr > 3]
print(greater_than_3)

# Elemento en la fila 0 y columna 1
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2d[0, 1])

1
[2 3]
[4 5]
2


## Álgebra lineal

In [19]:
import numpy as np

# Producto de dos matrices
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])
C = np.dot(A, B)
print(C)

# Cálculo de la inversa de una matriz
A_inv = np.linalg.inv(A)
print(A_inv)

# Resolver un sistema de ecuaciones lineales
coefficients = np.array([[2, 3], [1, -1]])
constants = np.array([5, 1])
solution = np.linalg.solve(coefficients, constants)

print(solution)

[[19 22]
 [43 50]]
[[-2.   1. ]
 [ 1.5 -0.5]]
[1.6 0.6]


## Diferencia usar Numpy y no usar Numpy

In [7]:
import time
import numpy as np

# Tamaño de la matriz
n = 100

# Crear matrices aleatorias sin NumPy
start_time = time.time()

matrix_a = [[i + j for j in range(n)] for i in range(n)]
matrix_b = [[i - j for j in range(n)] for i in range(n)]

result = [[0] * n for _ in range(n)]
for i in range(n):
    for j in range(n):
        for k in range(n):
            result[i][j] += matrix_a[i][k] * matrix_b[k][j]

end_time = time.time()
execution_time = end_time - start_time
print("Tiempo de ejecución en segundos sin NumPy:", execution_time)

# Crear matrices aleatorias con NumPy
start_time = time.time()

array_a = np.random.rand(n, n)
array_b = np.random.rand(n, n)

result_array = np.dot(array_a, array_b)

end_time = time.time()
execution_time = end_time - start_time
print("Tiempo de ejecución en segundos con NumPy:", execution_time)

Tiempo de ejecución en segundos sin NumPy: 0.4055674076080322
Tiempo de ejecución en segundos con NumPy: 0.0
